name: Generate GearMotorCalc.xlsx

on:
  push:
    branches: [ excel-template ]
  workflow_dispatch:

jobs:
  build-xlsx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: excel-template

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install XlsxWriter

      - name: Generate GearMotorCalc.xlsx
        run: |
          python tools/generate_gear_motor_calc.py

      - name: Commit GearMotorCalc.xlsx
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add GearMotorCalc.xlsx
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add GearMotorCalc.xlsx [skip ci]"
            git push origin excel-template
          fi
